### ISSUE TITLE
Support type casting

### ISSUE THREAD

**Issue by Piedone** [bijington/expressive#12]
It seems that the library currently doesn't support type casting, e.g. `(uint)5` will complain with "Unrecognised token 'uint'".

Would it be possible to implement this?

**Comment by bijington** [comment]
Apologies for the delay in replying I missed the notification. I will take some time to work out how best to go about implementing this. Out of interest does the `(uint)5` need to be written inside the expression itself or could it be supplied as a Parameter?

**Comment by Piedone** [comment]
In my case the expression comes from a string, so it would be part of the expression (unless I parse the expression myself...).

**Comment by bijington** [comment]
You are not actually the first person to mention being able to cast. Changing the parser to handle this (which I agree should probably be the ideal final result) will be rather involved and wouldn't fit in on the schedule for some time. Could the following work for you in the short term:

Implement a function that would handle the casting and be used along the lines of

`cast(5, uint)`

**Comment by Piedone** [comment]
That wouldn't work for me unfortunately, still the same issue.

But please don't bother, I've worked around this in some completely unrelated way - though it will be nice to see casting being supported by your library in the future.

**Comment by bijington** [comment]
OK I am glad you have found a work around for now. Out of interest can I ask how you managed to work around it? I am always keen to find out how people solve problems :).

**Comment by Piedone** [comment]
The input for my algorithm is a .NET abstract syntax tree. I decided to write an expression evaluator for a subset of the expressions (which involve a cast) instead of trying to interpret their strings. This is easier than parsing string expressions if you begin from scratch, but I'd rather have used an existing standard expression evaluator instead.

**Comment by bijington** [comment]
Closing this down as it is now possible through the `Integer`, `Decimal`, etc. functions. If we need more then we can add those
