### ISSUE TITLE
Capitalize function does not work as described

### ISSUE THREAD

**Issue by chrisg920** [bijington/expressive#138]
From the example in the readme for the capitalize() function:
capitalize('new year') : 'New Year'

This implies that the function should capitalize the first letter of each word in the string, but it does not. It only capitalizes the first letter of the string, e.g. 'New year'.  Looking at the source code, it is obvious that is what the code intended, but it seems it would be more useful if it worked as the example implies.

**Comment by bijington** [comment]
Expressive doesn't provide a Capitalize function. Are you sure this is the right repository?

**Comment by chrisg920** [comment]
My apologies, I had two Github tabs open at the same time and submitted the issue to the wrong one. Thanks for letting me know I messed up. 😊
