### ISSUE TITLE
Incorrect File Version in Expressive.dll

### ISSUE THREAD

**Issue by swhaworth** [bijington/expressive#144]
In the Nuget ExpressiveParser 3.0.0 package, the Expressive.dll has a file version of 0.0.0.0.  In the previous 2.5.0 package, the Expressive.dll had a file version of 2.5.0.0.

I am using Wix Toolset for my installer and it won't upgrade the file from 2.5.0 to 3.0.0 because of this issue, so I have to do a repair after an update.

It would be good if this could be fixed in the future!  Love your library!

**Comment by bijington** [comment]
@swhaworth thank you for pointing this out. https://www.nuget.org/packages/ExpressiveParser/3.0.1 should include a valid version.

Thank you for the kind words about the library too I really appreciate it!
