### ISSUE TITLE
Missing token, expecting ','

### ISSUE THREAD

**Issue by bluewalk** [bijington/expressive#16]
Hi there, I have a simple function for testing a rule taking 3 parameters
`Rule('a60f99fa-21ee-4dfa-b8c1-80ffaa3a83de', 10, 20)` 

This causes an error `Missing token, expecting ','`, if I change the first number to a string by enclosing them in '':
`Rule('a60f99fa-21ee-4dfa-b8c1-80ffaa3a83de', '10', 20)`
then the error goes away.

Why is this error appearing, it looks like the second integer after an integer messes things up. Eg this causes the same error `Test(12,33,44)`

_Update_
If I change it to `Rule('a60f99fa-21ee-4dfa-b8c1-80ffaa3a83de', 10,0, 20,0)` it works. But then the parameters are not integers anymore but decimals.

It seems that the comma after a number (for a second parameter) makes the parser think it's dealing with a decimal. Hence the space makes the parser think it's missing a comma.

Shouldn't the parser take a dot for decimals?

**Comment by bijington** [comment]
Thanks for raising the issue. It does look like a rather strange one. Out of interest what locale is your machine running? I know that commas are used for decimal separators in some parts of the world so it could well be related to that.

Unfortunately I am without my laptop for the next few days but when I am back with it I will look at this for you.

**Comment by bijington** [comment]
I do actually wonder if the parser is not handling the white space between the 2 integers and then believing the comma is a decimal separator. We should be able to fix that pretty easily.

**Comment by bluewalk** [comment]
It seems to only happen on integers though. As you said in your first comment it might have something to do with the locale. Mine is set to nl_NL, and we use comma's as a decimal separator instead of the dot. Unless we're coding of course, then it's a dot.

Guessing that when the parser uses InvariantCulture it might just fix the whole thing :)

**Comment by bijington** [comment]
I can confirm there is an issue around the parsing of an expression when the CurrentCulture uses a comma decimal separator. This has brought to light some other possible shortcomings so I propose to provide the following changes to resolve this issue:

1. Correct the GetNumber implementation to handle whitespace and ignore an ending decimal separator.
2. Provide a method of specifying what Culture to use when parsing and evaluating.

**Comment by bijington** [comment]
To try and explain the issue a little further the parser is accepting 10, as part of a valid number where it needs to discount the decimal separator if it is not followed by a number.

**Comment by bijington** [comment]
@bluewalk I believe I have a solution however I would like to ask a few questions to help make sure I make the right decision that benefits you.

1. You are obviously using integers in this example but if you were using a decimal what format would you expect to use:
10,0 or 10.0

Basically my plan is to prevent '10,' or '10.' from being passed as a valid number instead a number would have a trailing number after the decimal separator. I haven't stumbled across this as here in the UK we use the '.' decimal separator. I have the above working already plus I have added in the ability to specify the culture to use when creating an Expression to allow you to determine what decimal separator is used. If the above covers your answer to my question then I can go ahead and sort out a release.

**Comment by bluewalk** [comment]
@bijington Yes, I am expecting (as a programmer) to use 10.x instead of 10,x as the comma is used to separate parameters for a function in the expression. 

So basically I would be expecting that the following works:
```ExpressionFunctionA('somestring', 10, 20.5)```

**Comment by bijington** [comment]
@bluewalk thanks that is exactly the response I was hoping for :). I have a fix and will be performing a release very shortly.
