### ISSUE TITLE
Random function not implemented

### ISSUE THREAD

**Issue by TyelorD** [bijington/expressive#29]
I've found that while the documentation says Random() is supported, it is not yet implemented.

When using the Random() function in an expression the following exception is thrown:
`UnrecognisedTokenException: Unrecognised token 'R'`

The problem was very easy to fix however. To fix this I made the following changes:
Added Random.cs
```
using Expressive.Expressions;
using System;

namespace Expressive.Functions.Mathematical
{
    internal class RandomFunction : FunctionBase
    {
        #region FunctionBase Members

        public override string Name { get { return "Random"; } }

        public override object Evaluate(IExpression[] parameters)
        {
            this.ValidateParameterCount(parameters, 0, 0);

            return new Random().NextDouble();
        }

        #endregion
    }
}
```

Registered Random.cs to the ExpressionParser
```
// In constructor
// Mathematical
// ...
RegisterFunction(new RandomFunction());
// ...
```

Note that this also exposed a bug with Functions requiring 0 parameters.

To solve this issue, I had to change the following line in FunctionBase.cs
```
if (expectedCount != -1 && (parameters == null || !parameters.Any() || parameters.Length != expectedCount))
```
to the following:
```
if (expectedCount != -1 && (parameters == null || parameters.Length != expectedCount))
```

This may have unintended consequences, however preliminary tests show no change in function after my changes, minus the ability to use the Random() function inside of an Expression.

If you have any questions, want more details, or would like me to pull and request a merge with the changes just let me know!

**Comment by TyelorD** [comment]
@bijington 

Of course! Thank you for this awesome library :slightly_smiling_face: !

I'm currently using the 1.1.0 version for C# .NET, which I assumed was the latest release as that is what is listed in the Readme as the supported language release for GitHub.

Looking at the source on GitHub however it does seem that I must be using an older version, as there is definitely a Random.cs IFunction class listed in the Source folder. However on the release I downloaded this was not included.

I'm going to clone the repo so that I can have the latest version then since this is a nonissue for the latest version.

Thanks again for the awesome tool and for the response!!
-Tyelor Klein

**Comment by TyelorD** [comment]
@bijington Oh don't worry about it! The old version still worked just fine for me :slightly_smiling_face: and I'm glad I could help a little bit, and I'll be watching for the next release too!

I did need to change a few components of Expressive to get it to play nicely with my Mod system, as I'm passing a custom class to the expressions. As an aside some dlls are multi-platform in Unity, it (understandably) doesn't recompile dlls when building a project, so it's safer to include the source code if you can. That way it will be compiled for each platform you're targeting with your Unity project.

As for Nuget, I'm not sure how to use it and haven't done so in the past. So I have no idea if it works with Unity...

**Comment by bijington** [comment]
@TyelorD yes that makes sense re: compiling the source. I will leave this bug open as a reminder to myself that I need to correct my versioning when I do the next release.

**Comment by bijington** [comment]
@TyelorD one thing I forgot to ask, what components did you need to change in Expressive? If they are potentially generic changes then I would be happy to consider including them in the main framework.

**Comment by TyelorD** [comment]
@bijington sorry for the late response, but I changed Numbers.cs, specifically the check if the object is a string, I also check if it's my custom object and if it is I get the property I want from it for the expression.

A more generic solution might be using the object's ToString method and attempting a double.TryParse on that string, and using the value it returns if the TryParse succeeds.

This probably isn't the best solution though, and I think would be fairly slow with the TryParse...

**Comment by bijington** [comment]
@TyelorD likewise on the apologies for a delayed response. The main reason I asked was because I am working through a fair amount of refactoring. If most of your changes are in Numbers.cs then you should be ok as I haven't made many if any changes in there so far.

One option may to allow users to register types and a method on obtaining their value. Something like registering a Func<T, U> that would allow you to define how the value is returned if the type is encountered. I would expect that might perform better than `TryParse` everywhere.

**Comment by bijington** [comment]
Closing this issue down as the Random function does exist as discovered on the comment trail.
