### ISSUE TITLE
Strong name key

### ISSUE THREAD

**Issue by troplin** [bijington/expressive#30]
Consider signing this assembly with a strong name key. Otherwise it cannot be used by other assemblies that are signed themselves.

**Comment by bijington** [comment]
Hi @troplin, I am more than happy to implement this in the next release.

Thanks

**Comment by bijington** [comment]
This will be the next item on my list. Details to aid my implementation are here:

https://docs.microsoft.com/en-us/dotnet/framework/app-domains/create-and-use-strong-named-assemblies

**Comment by bijington** [comment]
@troplin this is now in the latest version (1.4.0)

**Comment by troplin** [comment]
This is great news, thanks!
