### ISSUE TITLE
Scientific notation

### ISSUE THREAD

**Issue by Larry57** [bijington/expressive#38]
Hi,

I used 1E6  instead of 1000000 as a litteral for a number, unfortunately Expressive does not seems to like it.

Despite this detail, this library is a joy to use. Thanks a lot !!!

**Comment by bijington** [comment]
This is one of the few things I didn’t include when trying to match NCalc as I didn’t have a use case... until now 🙂.

It might not make it in to the upcoming release but I am happy to add it in.

**Comment by bijington** [comment]
This is now ready for the upcoming release
